[package]
name = "cgraphics"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
eframe = "0.31.1"
egui_extras = "0.31.1"
epaint = "0.31.1"
image = "0.25.6"
nalgebra = "0.33.2"
rayon = "1.10.0"
serde_json = "1.0.140"
